from dataclasses import replace
import hashlib
import json
import shutil
from pathlib import Path

import pytest

from cabbage_detection.release_artifacts import load_release_manifest


# A synthetic manifest whose digests are placeholders. It lives here rather
# than beside the real one, which is generated by build_release_manifest.py,
# so a fixture can never be mistaken for a publishable release manifest.
MANIFEST = Path("tests/release/fixture-manifest.json")


@pytest.fixture
def release_fixture(tmp_path: Path):
    approved = load_release_manifest(MANIFEST)
    records = []
    for record in approved.checkpoints:
        payload = f"{record.model_name}:{record.condition}".encode("utf-8")
        source_path = f"runs/reproduced/{record.model_name}/checkpoints/best.pt"
        metadata_path = tmp_path / record.metadata_path
        metadata_path.parent.mkdir(parents=True, exist_ok=True)
        metadata_path.write_text(
            json.dumps({
                "run_id": record.run_id,
                "command": ["scripts/train.py", "--config", f"configs/torchvision/{record.model_name}.yaml"],
                "result_status": "reproduced_verified",
                "status": "succeeded",
                "outputs": {
                    "best_checkpoint": {
                        "path": "checkpoints/best.pt",
                        "sha256": hashlib.sha256(payload).hexdigest(),
                        "size_bytes": len(payload),
                    }
                },
            }),
            encoding="utf-8",
        )
        synthetic = replace(
            record,
            source_path=source_path,
            size_bytes=len(payload),
            sha256=hashlib.sha256(payload).hexdigest(),
        )
        source = tmp_path / synthetic.source_path
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_bytes(payload)
        records.append(synthetic)
    # Archives bundle the repository's licence and notice texts verbatim.
    for relative in ("LICENSE", "LICENSES", "weights/notices"):
        source = Path(relative)
        target = tmp_path / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.is_dir():
            shutil.copytree(source, target)
        else:
            shutil.copy2(source, target)
    manifest = approved.with_checkpoints(tuple(records))
    return tmp_path, manifest, tmp_path / "dist/release"
